<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Dashboard.Domain\Dashboard.Domain.csproj" />
		<ProjectReference Include="..\Dashboard.Application\Dashboard.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="BuildingBlocks.Contracts">
			<HintPath>..\Library\BuildingBlocks.Contracts.dll</HintPath>
		</Reference>
		<Reference Include="BuildingBlocks.CrossCutting">
			<HintPath>..\Library\BuildingBlocks.CrossCutting.dll</HintPath>
		</Reference>
		<Reference Include="BuildingBlocks.SharedKernel">
			<HintPath>..\Library\BuildingBlocks.SharedKernel.dll</HintPath>
		</Reference>
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
