// <auto-generated />
using System;
using Dashboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dashboard_sch")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalytical", b =>
                {
                    b.Property<long>("AnalyticalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnalyticalId"));

                    b.Property<string>("AnalyticalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("analytical_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DimensionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimension_type");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("AnalyticalId")
                        .HasName("dim_analytical_pkey");

                    b.HasIndex("AnalyticalCode")
                        .HasDatabaseName("ix_dim_analytical_code");

                    b.HasIndex("DimensionType")
                        .HasDatabaseName("ix_dim_analytical_dimension_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_dim_analytical_active")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("AnalyticalCode", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_analytical_code_version");

                    b.HasIndex("AnalyticalCode", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_dim_analytical_effective_period");

                    b.ToTable("dim_analytical", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", b =>
                {
                    b.Property<long>("AnalyticalItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnalyticalItemId"));

                    b.Property<long>("AnalyticalId")
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_value");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_item_id");

                    b.Property<decimal?>("RangeFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("range_from");

                    b.Property<decimal?>("RangeTo")
                        .HasColumnType("numeric")
                        .HasColumnName("range_to");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AnalyticalItemId")
                        .HasName("dim_analytical_item_pkey");

                    b.HasIndex("AnalyticalId")
                        .HasDatabaseName("ix_dim_analytical_item_analytical");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("ix_dim_analytical_item_code");

                    b.HasIndex("ParentItemId")
                        .HasDatabaseName("ix_dim_analytical_item_parent");

                    b.HasIndex("AnalyticalId", "IsActive")
                        .HasDatabaseName("ix_dim_analytical_item_active")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("AnalyticalId", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_analytical_item_code");

                    b.HasIndex("AnalyticalId", "SortOrder")
                        .HasDatabaseName("ix_dim_analytical_item_sort");

                    b.ToTable("dim_analytical_item", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItemTranslation", b =>
                {
                    b.Property<long>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("translation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TranslationId"));

                    b.Property<long>("AnalyticalItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_name");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TranslationId")
                        .HasName("dim_analytical_item_translation_pkey");

                    b.HasIndex("AnalyticalItemId")
                        .HasDatabaseName("ix_analytical_item_translation_item");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_analytical_item_translation_language");

                    b.HasIndex("AnalyticalItemId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("uq_analytical_item_translation_language");

                    b.ToTable("dim_analytical_item_translation", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRule", b =>
                {
                    b.Property<long>("AnalyticalRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnalyticalRuleId"));

                    b.Property<long>("AnalyticalId")
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_id");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("AnalyticalRuleId")
                        .HasName("dim_analytical_rule_pkey");

                    b.HasIndex("AnalyticalId")
                        .HasDatabaseName("ix_analytical_rule_analytical");

                    b.HasIndex("RuleCode")
                        .HasDatabaseName("ix_analytical_rule_code");

                    b.HasIndex("AnalyticalId", "IsActive")
                        .HasDatabaseName("ix_analytical_rule_active")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("AnalyticalId", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_analytical_rule_effective_period");

                    b.HasIndex("AnalyticalId", "RuleCode", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_analytical_rule_code_version");

                    b.ToTable("dim_analytical_rule", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRuleCondition", b =>
                {
                    b.Property<long>("AnalyticalRuleConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_rule_condition_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnalyticalRuleConditionId"));

                    b.Property<long>("AnalyticalItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_item_id");

                    b.Property<long>("AnalyticalRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("analytical_rule_id");

                    b.Property<int>("ConditionOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("condition_order");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("operator");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_field");

                    b.Property<string>("ValueFrom")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value_from");

                    b.Property<string>("ValueTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value_to");

                    b.Property<string>("Values")
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.HasKey("AnalyticalRuleConditionId")
                        .HasName("dim_analytical_rule_condition_pkey");

                    b.HasIndex("AnalyticalItemId")
                        .HasDatabaseName("ix_analytical_rule_condition_item");

                    b.HasIndex("AnalyticalRuleId")
                        .HasDatabaseName("ix_analytical_rule_condition_rule");

                    b.HasIndex("SourceField")
                        .HasDatabaseName("ix_analytical_rule_condition_source_field");

                    b.HasIndex("AnalyticalRuleId", "ConditionOrder")
                        .HasDatabaseName("ix_analytical_rule_condition_order");

                    b.ToTable("dim_analytical_rule_condition", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.DimAdministrativeUnit", b =>
                {
                    b.Property<long>("AdministrativeUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("administrative_unit_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EffectiveFrom")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from");

                    b.Property<int?>("EffectiveTo")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_code");

                    b.Property<short?>("UnitTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("unit_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AdministrativeUnitId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_dim_administrative_unit_active");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_dim_administrative_unit_parent");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_administrative_unit_code_effective");

                    b.ToTable("dim_administrative_unit", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.DimAgeRange", b =>
                {
                    b.Property<int>("AgeRangeId")
                        .HasColumnType("integer")
                        .HasColumnName("age_range_id");

                    b.Property<short>("AgeFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("age_from");

                    b.Property<short>("AgeTo")
                        .HasColumnType("smallint")
                        .HasColumnName("age_to");

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("colour");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AgeRangeId");

                    b.HasIndex("AgeFrom", "AgeTo")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_age_range_from_to");

                    b.ToTable("dim_age_range", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.DimCatalogItem", b =>
                {
                    b.Property<string>("CatalogName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("catalog_name");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<int>("EffectiveFrom")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EffectiveTo")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CatalogName", "Code", "EffectiveFrom");

                    b.HasIndex("CatalogName", "IsActive")
                        .HasDatabaseName("ix_dim_catalog_items_active");

                    b.ToTable("dim_catalog_items", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.DimIndustry", b =>
                {
                    b.Property<long>("IndustryId")
                        .HasColumnType("bigint")
                        .HasColumnName("industry_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EffectiveFrom")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from");

                    b.Property<int?>("EffectiveTo")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IndustryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_dim_industry_active");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_dim_industry_level");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_dim_industry_parent");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_industry_code_effective");

                    b.ToTable("dim_industry", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.DimOccupation", b =>
                {
                    b.Property<long>("OccupationId")
                        .HasColumnType("bigint")
                        .HasColumnName("occupation_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EffectiveFrom")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from");

                    b.Property<int?>("EffectiveTo")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OccupationId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_dim_occupation_active");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_dim_occupation_level");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_dim_occupation_parent");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_dim_occupation_code_effective");

                    b.ToTable("dim_occupation", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Snapshot.LabourEmploymentSnapshot", b =>
                {
                    b.Property<long>("LabourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("labour_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LabourId"));

                    b.Property<string>("ContractCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_code");

                    b.Property<short>("EconomicActivitiesCode")
                        .HasColumnType("smallint")
                        .HasColumnName("economic_activities_code");

                    b.Property<string>("EducationLevelCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("education_level_code");

                    b.Property<string>("EmployerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employer_code");

                    b.Property<string>("EmployerSectorsCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employer_sectors_code");

                    b.Property<DateTime?>("EmploymentStatusDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employment_status_date");

                    b.Property<bool?>("EverWorked")
                        .HasColumnType("boolean")
                        .HasColumnName("ever_worked");

                    b.Property<bool?>("IndustrialZoneStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("industrial_zone_status");

                    b.PrimitiveCollection<string[]>("IndustryCodes")
                        .HasColumnType("text[]")
                        .HasColumnName("industry_codes");

                    b.Property<string>("JobSearchStatus")
                        .HasColumnType("text")
                        .HasColumnName("job_search_status");

                    b.Property<bool?>("JobSearchWanted")
                        .HasColumnType("boolean")
                        .HasColumnName("job_search_wanted");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<string>("JobTypesCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_types_code");

                    b.Property<string>("MajorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("major_code");

                    b.Property<string>("MajorDescription")
                        .HasColumnType("text")
                        .HasColumnName("major_description");

                    b.Property<int?>("NumberOfJobs")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_jobs");

                    b.Property<string>("OccupationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("occupation_code");

                    b.Property<string>("ParticipationFormCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("participation_form_code");

                    b.Property<string>("PositionGroupsCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_groups_code");

                    b.PrimitiveCollection<string[]>("PriorityCodes")
                        .HasColumnType("text[]")
                        .HasColumnName("priority_codes");

                    b.Property<DateTime?>("SiEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("si_end_date");

                    b.Property<DateTime?>("SiStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("si_start_date");

                    b.Property<string>("SkillIndustryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("skill_industry_code");

                    b.Property<string>("SkillLevelCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("skill_level_code");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_version");

                    b.Property<string>("SocialInsuranceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("social_insurance_number");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<string>("TechnicalLevelCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technical_level_code");

                    b.Property<int?>("TotalWorkExperience")
                        .HasColumnType("integer")
                        .HasColumnName("total_work_experience");

                    b.Property<string>("UneconomicReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uneconomic_reason_code");

                    b.Property<bool?>("UnemploymentBenefitStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("unemployment_benefit_status");

                    b.Property<int?>("UnemploymentDuration")
                        .HasColumnType("integer")
                        .HasColumnName("unemployment_duration");

                    b.Property<string>("UnemploymentReason")
                        .HasColumnType("text")
                        .HasColumnName("unemployment_reason");

                    b.Property<DateTime?>("UnemploymentStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unemployment_start_date");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("work_location");

                    b.HasKey("LabourId")
                        .HasName("pk_labour_employment_snapshot");

                    b.HasIndex("EconomicActivitiesCode")
                        .HasDatabaseName("ix_labour_employment_snapshot_economic");

                    b.HasIndex("EmployerCode")
                        .HasDatabaseName("ix_labour_employment_snapshot_employer");

                    b.HasIndex("OccupationCode")
                        .HasDatabaseName("ix_labour_employment_snapshot_occupation");

                    b.HasIndex("SkillIndustryCode")
                        .HasDatabaseName("ix_labour_employment_snapshot_industry");

                    b.HasIndex("SnapshotVersion")
                        .HasDatabaseName("ix_labour_employment_snapshot_version");

                    b.ToTable("labour_employment_snapshot", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Snapshot.LabourIdentitySnapshot", b =>
                {
                    b.Property<long>("LabourId")
                        .HasColumnType("bigint")
                        .HasColumnName("labour_id");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("AccType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acc_type");

                    b.Property<string>("CccdNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cccd_number");

                    b.Property<string>("CmndNumber")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cmnd_number");

                    b.Property<string>("CurrentAddressCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_address_code");

                    b.Property<string>("CurrentAddressDetail")
                        .HasColumnType("text")
                        .HasColumnName("current_address_detail");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EthnicCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ethnic_code");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender_code");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("text")
                        .HasColumnName("issue_place");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("marital_status");

                    b.Property<string>("PermanentAddressCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permanent_address_code");

                    b.Property<string>("PermanentAddressDetail")
                        .HasColumnType("text")
                        .HasColumnName("permanent_address_detail");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ReligionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("religion_code");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_version");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.HasKey("LabourId", "DateOfBirth")
                        .HasName("pk_labour_identity_snapshot");

                    b.ToTable("labour_identity_snapshot", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Summary.LabourEconomicStatusSummary", b =>
                {
                    b.Property<long>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SummaryId"));

                    b.Property<string>("AdministrativeUnitCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrative_unit_code");

                    b.Property<DateTimeOffset>("AggregatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aggregated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("AnalyticalDefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("analytical_definition_version");

                    b.Property<string>("ByAgeGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_age_group")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ByGender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_gender")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ByIndustry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_industry")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ByPriority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_priority")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("EconomicStatusCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("economic_status_code");

                    b.Property<string>("EducationLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("education_level_code");

                    b.Property<long>("LabourCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("labour_count");

                    b.Property<long?>("ProcessingRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_run_id");

                    b.Property<DateOnly>("ReferencePeriod")
                        .HasColumnType("date")
                        .HasColumnName("reference_period");

                    b.Property<long>("SourceEmploymentSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_employment_snapshot_version");

                    b.Property<long>("SourceIdentitySnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_identity_snapshot_version");

                    b.Property<string>("TechnicalLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technical_level_code");

                    b.HasKey("SummaryId")
                        .HasName("labour_economic_status_summary_pkey");

                    b.HasIndex("AdministrativeUnitCode")
                        .HasDatabaseName("ix_labour_economic_status_summary_admin");

                    b.HasIndex("EconomicStatusCode")
                        .HasDatabaseName("ix_labour_economic_status_summary_status");

                    b.HasIndex("ReferencePeriod")
                        .HasDatabaseName("ix_labour_economic_status_summary_period");

                    b.HasIndex("ReferencePeriod", "AdministrativeUnitCode")
                        .HasDatabaseName("ix_labour_economic_status_summary_period_admin");

                    b.HasIndex("AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode")
                        .HasDatabaseName("ix_labour_economic_status_summary_filter");

                    b.HasIndex("ReferencePeriod", "AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode", "EconomicStatusCode")
                        .IsUnique()
                        .HasDatabaseName("uq_labour_economic_status_summary_grain");

                    b.ToTable("labour_economic_status_summary", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Summary.LabourIdentitySummary", b =>
                {
                    b.Property<long>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SummaryId"));

                    b.Property<string>("AdministrativeUnitCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrative_unit_code");

                    b.Property<string>("AgeGroupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("age_group_code");

                    b.Property<DateTimeOffset>("AggregatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aggregated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("AnalyticalDefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("analytical_definition_version");

                    b.Property<string>("ByIndustry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_industry")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ByPriority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("by_priority")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("EconomicStatusCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("economic_status_code");

                    b.Property<string>("EducationLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("education_level_code");

                    b.Property<long>("LabourCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("labour_count");

                    b.Property<long?>("MaleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("male_count");

                    b.Property<long?>("ProcessingRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_run_id");

                    b.Property<long>("SourceEmploymentSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_employment_snapshot_version");

                    b.Property<long>("SourceIdentitySnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_identity_snapshot_version");

                    b.Property<string>("TechnicalLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technical_level_code");

                    b.Property<string>("TopLevelOccupationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("top_level_occupation_code");

                    b.HasKey("SummaryId")
                        .HasName("labour_identity_summary_pkey");

                    b.HasIndex("AgeGroupCode")
                        .HasDatabaseName("ix_labour_identity_summary_age");

                    b.HasIndex("EconomicStatusCode")
                        .HasDatabaseName("ix_labour_identity_summary_status");

                    b.HasIndex("TopLevelOccupationCode")
                        .HasDatabaseName("ix_labour_identity_summary_occupation");

                    b.HasIndex("AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode")
                        .HasDatabaseName("ix_labour_identity_summary_filter");

                    b.HasIndex("AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode", "TopLevelOccupationCode", "AgeGroupCode", "EconomicStatusCode")
                        .IsUnique()
                        .HasDatabaseName("uq_labour_identity_summary_grain");

                    b.ToTable("labour_identity_summary", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Summary.LabourTimeSummary", b =>
                {
                    b.Property<long>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SummaryId"));

                    b.Property<string>("AdministrativeUnitCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrative_unit_code");

                    b.Property<DateTimeOffset>("AggregatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aggregated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("AnalyticalDefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("analytical_definition_version");

                    b.Property<string>("EducationLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("education_level_code");

                    b.Property<bool>("IsRevised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revised");

                    b.Property<long>("OutWorkingAgeLabourCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("out_working_age_labour_count");

                    b.Property<long?>("PreviousOutWorkingAgeLabourCount")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_out_working_age_labour_count");

                    b.Property<long?>("PreviousTotalLabourCount")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_total_labour_count");

                    b.Property<long?>("PreviousWorkingAgeLabourCount")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_working_age_labour_count");

                    b.Property<long?>("ProcessingRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_run_id");

                    b.Property<DateOnly>("ReferencePeriod")
                        .HasColumnType("date")
                        .HasColumnName("reference_period");

                    b.Property<DateTimeOffset?>("RevisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revised_at");

                    b.Property<long>("SourceEmploymentSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_employment_snapshot_version");

                    b.Property<long>("SourceIdentitySnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_identity_snapshot_version");

                    b.Property<string>("TechnicalLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technical_level_code");

                    b.Property<long>("TotalLabourCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_labour_count");

                    b.Property<short>("WorkingAgeFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)15)
                        .HasColumnName("working_age_from");

                    b.Property<long>("WorkingAgeLabourCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("working_age_labour_count");

                    b.Property<short>("WorkingAgeTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)62)
                        .HasColumnName("working_age_to");

                    b.HasKey("SummaryId")
                        .HasName("labour_time_summary_pkey");

                    b.HasIndex("IsRevised")
                        .HasDatabaseName("ix_labour_time_summary_revised");

                    b.HasIndex("ReferencePeriod")
                        .HasDatabaseName("ix_labour_time_summary_period");

                    b.HasIndex("ReferencePeriod", "AdministrativeUnitCode")
                        .HasDatabaseName("ix_labour_time_summary_period_admin");

                    b.HasIndex("AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode")
                        .HasDatabaseName("ix_labour_time_summary_filter");

                    b.HasIndex("ReferencePeriod", "AdministrativeUnitCode", "EducationLevelCode", "TechnicalLevelCode")
                        .IsUnique()
                        .HasDatabaseName("uq_labour_time_summary_grain");

                    b.ToTable("labour_time_summary", "dashboard_sch");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalytical", "Analytical")
                        .WithMany("Items")
                        .HasForeignKey("AnalyticalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_dim_analytical_item_analytical");

                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", "ParentItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_dim_analytical_item_parent");

                    b.Navigation("Analytical");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItemTranslation", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", "AnalyticalItem")
                        .WithMany("Translations")
                        .HasForeignKey("AnalyticalItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_analytical_item_translation_item");

                    b.Navigation("AnalyticalItem");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRule", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalytical", "Analytical")
                        .WithMany("Rules")
                        .HasForeignKey("AnalyticalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_analytical_rule_analytical");

                    b.Navigation("Analytical");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRuleCondition", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", "AnalyticalItem")
                        .WithMany("RuleConditions")
                        .HasForeignKey("AnalyticalItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_analytical_rule_condition_item");

                    b.HasOne("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRule", "AnalyticalRule")
                        .WithMany("Conditions")
                        .HasForeignKey("AnalyticalRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_analytical_rule_condition_rule");

                    b.Navigation("AnalyticalItem");

                    b.Navigation("AnalyticalRule");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalytical", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RuleConditions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Dimension.Analytical.DimAnalyticalRule", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
